### ISSUE TITLE
Make initial Proof of Concept

### ISSUE THREAD

**Issue by i-pitt** [NickThorne123/db_bench#24]
TBC

Stretch: Working demo of one database on a basic GUI

**Comment by NickThorne123** [comment]
I will answer the email of 7th March here

_Good afternoon Nick,

We have reached the stage in the project where we are starting to look at setting up Docker containers and connecting to the database, however we have run into a few difficulties. At present, we have the GUI working, but only with mock data and we can't connect it to the backend. We were unable to find the launch.json (for configuring VS Code) and example.env files to set up the application, and as a result we've become a little confused.

We were wondering if you would be able to give us a brief demo on how to install the initial application on GitHub, after cloning the repository. With the end of Sprint 2 being next week, we understand we haven't asked with a lot of notice, but if there is an available time between now and next Thursday when you would be able to assist us, we would be very grateful.

Many Thanks,
Iona_

and

_Also, on top of this, can I ask if we need to install a python interpreter in order to make use of a venv from here: https://www.python.org/downloads/ and if so, what version would you recommend/ like us to use?_

**Comment by NickThorne123** [comment]
Relating to the second question [B]

Yes , the [VSCode instructions](https://code.visualstudio.com/docs/python/python-tutorial) say that you do need to install a Python interpreter on Windows.

**Comment by NickThorne123** [comment]
Links from Telco

https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql
https://stackoverflow.com/questions/5016505/mysql-grant-all-privileges-on-database
https://clickhouse.com/docs/en/operations/settings/settings-users
